### ISSUE TITLE
Epic: Enable JUnit testing the UI

### ISSUE THREAD

**Issue by caalador** [vaadin/testbench#1326]
This is the epic ticket for following the UI JUnit test feature development.

DOD for features: feature is implemented, there is a test, documentation for feature exists

Testing features:
- [ ] Create a base class for setup and teardown of a UITest #
- [ ] Create a base class for setup and teardown of a SpringUITest #
- [ ] Enable PrettyPrintTree output for failed UITest #
- [ ] Implement navigation so that the instantiated view is returned #
- [ ] Implement component search with fluent API #
- [ ] Implement generic test wrapper for components #
- [ ] Create test wrapper for TextField #
- [ ] Create test wrapper for Button #
- [ ] Create test wrapper for Notification #
- [ ] Test HelloWorld from start.vaadin.com
- [ ] Bring in required kotlin files instead of using full dependency #
- [ ] More to be added...
