### ISSUE TITLE
Add more component query helpers.

### ISSUE THREAD

**Issue by caalador** [vaadin/testbench#1370]
Create methods in ComponentQuery for all possible LocatorSpecifications.

- [x] caption #1384 
- [x] ~~placeholder~~ (see #1357)
- [x] text #1385 
- [x] count: exact, range, max, min #1374 
- [x] value #1388 
- [x] applied CSS classes #1373 
- [x] not applied CSS classes #1373

**Comment by knoobie** [comment]
Just putting the ideas here; not sure if you already wanna have separate tickets in this early stage. 

You often use the theme attribute to apply custom styling to components, so it would be awesome to search for them, like you allow with classes (that aren't so common with components) (mentioned in the other PR)

Additionally it would be good to add generic hasAttribute(String attribute) and hasAttribute(String attribute, String value) to search components by custom attributes like aria-label, aria-hidden and so on.

**Comment by mcollovati** [comment]
Thanks again for your feedback.
Do you mind open two separate issues for theme and attribute helpers?
